= 3 Writing Makefiles
:toc: left

* The information that tells `make` how to recompile a system comes from
  reading a data base called the _makefile_.

== 3.1 What Makefiles Contain

* Makefiles contain five kinds of things: _explicit rules_, _implicit rules_,
  _variable definitions_, _directives_, and _comments_.
* Rules, variables, and directives are described at length in later chapters.

'''

* An _explicit rule_ says when and how to remake one or more files, called the
  rule's _targets_. +
  It lists the other files that the targets depend on, called the
  _prerequisites_ of the target, and may also give a recipe to use to create
  or update the targets. +
  See Chapter 4 [Writing Rules], page 23.
* An _implicit rule_ says when and how to remake a class of files based on
  their names. +
  It describes how a target may depend on a file with a name similar to the
  target and gives a recipe to create or update such a target. +
  See Chapter 10 [Using Implicit Rules], page 121.
* A _variable definition_ is a line that specifies a text string value for a
  variable that can be substituted into the text later. +
  The simple makefile example shows a variable definition for `objects` as a
  list of all object files (see Section 2.4 [Variables Make Makefiles
  Simpler], page 6).
* A _directive_ is an instruction for `make` to do something special while
  reading the makefile. +
  These include:
** Reading another makefile (see Section 3.3 [Including Other Makefiles], page
   13).
** Deciding (based on the values of variables) whether to use or ignore a part
   of the makefile (see Chapter 7 [Conditional Parts of Makefiles], page 85).
** Defining a variable from a verbatim string containing multiple lines (see
   Section 6.8 [Defining Multi-Line Variables], page 76).
* '```\#```' in a line of a makefile starts a _comment_. +
  It and the rest of the line are ignored, except that a trailing backslash
  not escaped by another backslash will continue the comment across multiple
  lines. +
  A line containing just a comment (with perhaps spaces before it) is
  effectively blank, and is ignored. +
  If you want a literal `#`, escape it with a backslash (e.g., `\#`). +
  Comments may appear on any line in the makefile, although they are treated
  specially in certain situations.
+
'''
+
You cannot use comments within variable references or function calls: any
instance of `#` will be treated literally (rather than as the start of a
comment) inside a variable reference or function call. +
Comments within a recipe are passed to the shell, just as with any other
recipe text. +
The shell decides how to interpret it: whether or not this is a comment is up
to the shell.
+
'''
+
Within a `define` directive, comments are not ignored during the definition of
the variable, but rather kept intact in the value of the variable. +
When the variable is expanded they will either be treated as `make` comments
or as recipe text, depending on the context in which the variable is
evaluated.

=== 3.1.1 Splitting Long Lines

* Makefiles use a "line-based" syntax in which the newline character is
  special and marks the end of a statement.
* GNU `make` has no limit on the length of a statement line, up to the amount
  of memory in your computer.

'''

* However, it is difficult to read lines which are too long to display without
  wrapping or scrolling.
* So, you can format your makefiles for readability by adding newlines into
  the middle of a statement: you do this by escaping the internal newlines
  with a backslash (`\`) character.
* Where we need to make a distinction we will refer to "physical lines" as a
  single line ending with a newline (regardless of whether it is escaped) and
  a "logical line" being a complete statement including all escaped newlines
  up to the first non-escaped newline.

'''

* The way in which backslash/newline combinations are handled depends on
  whether the statement is a recipe line or a non-recipe line.
* Handling of backslash/newline in a recipe line is discussed later (see
  Section 5.1.1 [Splitting Recipe Lines], page 45).

'''

* Outside of recipe lines, backslash/newlines are converted into a single
  space character.
* Once that is done, all whitespace around the backslash/newline is condensed
  into a single space: this includes all whitespace preceding the backslash,
  all whitespace at the beginning of the line after the backslash/newline, and
  any consecutive backslash/newline combinations.

'''

* If the `.POSIX` special target is defined then backslash/newline handling is
  modified slightly to conform to POSIX.2: first, whitespace preceding a
  backslash is not removed and second, consecutive backslash/newlines are not
  condensed.

==== Splitting Without Adding Whitespace

* If you need to split a line but do not want any whitespace added, you can
  utilize a subtle trick: replace your backslash/newline pairs with the three
  characters dollar sign, backslash, and newline:

[source,makefile]
var := one$\
	word

* After `make` removes the backslash/newline and condenses the following line
  into a single space, this is equivalent to:

[source,makefile]
var := one$ word

'''

* Then `make` will perform variable expansion.
* The variable reference '```$ ```' refers to a variable with the
  one-character name "``` ```" (space) which does not exist, and so expands to
  the empty string, giving a final assignment which is the equivalent of:

[source,makefile]
var := oneword

== 3.3 Including Other Makefiles

* The `include` directive tells `make` to suspend reading the current makefile
  and read one or more other makefiles before continuing.
* The directive is a line in the makefile that looks like this:

[source,makefile,subs="+quotes"]
include _filenames_...

* _filenames_ can contain shell file name patterns.
* If _filenames_ is empty, nothing is included and no error is printed.

'''

* Extra spaces are allowed and ignored at the beginning of the line, but the
  first character must not be a tab (or the value of `.RECIPEPREFIX`) -- if
  the line begins with a tab, it will be considered a recipe line.
* Whitespace is required between `include` and the file names, and between
  file names; extra whitespace is ignored there and at the end of the
  directive.
* A comment starting with '```#```' is allowed at the end of the line.
* If the file names contain any variable or function references, they are
  expanded.
* See Chapter 6 [How to Use Variables], page 65.

'''

* For example, if you have three `.mk` files, `a.mk`, `b.mk`, and `c.mk`, and
  `$(bar)` expands to `bish bash`, then the following expression
+
[source,makefile]
include foo *.mk $(bar)
+
is equivalent to
+
[source,makefile]
include foo a.mk b.mk c.mk bish bash

* When `make` processes an `include` directive, it suspends reading of the
  containing makefile and reads from each listed file in turn.
* When that is finished, `make` resumes reading the makefile in which the
  directive appears.

'''

* One occasion for using `include` directives is when several programs,
  handled by individual makefiles in various directories, need to use a common
  set of variable definitions (see Section 6.5 [Setting Variables], page 72)
  or pattern rules (see Section 10.5 [Defining and Redefining Pattern Rules],
  page 129).

'''

* Another such occasion is when you want to generate prerequisites from source
  files automatically; the prerequisites can be put in a file that is included
  by the main makefile.
* This practice is generally cleaner than that of somehow appending the
  prerequisites to the end of the main makefile as has been traditionally done
  with other versions of `make`.
* See Section 4.13 [Automatic Prerequisites], page 42.

'''

* If the specified name does not start with a slash (or a drive letter and
  colon when GNU Make is compiled with MS-DOS / MS-Windows path support), and
  the file is not found in the current directory, several other directories
  are searched.
* First, any directories you have specified with the '```-I```' or
  '```--include-dir```' options are searched (see Section 9.8 [Summary of
  Options], page 114).
* Then the following directories (if they exist) are searched, in this order:
  `_prefix_/include` (normally `/usr/local/include`{empty}footnote:[GNU Make
  compiled for MS-DOS and MS-Windows behaves as if _prefix_ has been defined
  to be the root of the DJGPP tree hierarchy]) /usr/gnu/include,
  `/usr/local/include`, `/usr/include`.

'''

* The `.INCLUDE_DIRS` variable will contain the current list of directories
  that `make` will search for included files.
* See Section 6.14 [Other Special Variables], page 80.

'''

* You can avoid searching in these default directories by adding the command
  line option `-I` with the special value `-` (e.g., `-I-`) to the command
  line.
* This will cause `make` to forget any already-set `include` directories,
  including the default directories.

'''

* If an included makefile cannot be found in any of these directories it is
  not an immediately fatal error; processing of the makefile containing the
  `include` continues.
* Once it has finished reading makefiles, `make` will try to remake any that
  are out of date or don't exist.
* See Section 3.5 [How Makefiles Are Remade], page 15.
* Only after it has failed to find a rule to remake the makefile, or it found
  a rule but the recipe failed, will `make` diagnose the missing makefile as a
  fatal error.

'''

* If you want `make` to simply ignore a makefile which does not exist or
  cannot be remade, with no error message, use the `-include` directive
  instead of `include`, like this:

[source,makefile,subs="+quotes"]
-include _filenames_...

* This acts like `include` in every way except that there is no error (not
  even a warning) if any of the filenames (or any prerequisites of any of the
  _filenames_) do not exist or cannot be remade.
* For compatibility with some other `make` implementations, `sinclude` is
  another name for `-include`.

== 3.5 How Makefiles Are Remade

* Sometimes makefiles can be remade from other files, such as RCS or SCCS
  files.
* If a makefile can be remade from other files, you probably want `make` to
  get an up-to-date version of the makefile to read in.

'''

* To this end, after reading in all makefiles `make` will consider each as a
  goal target, in the order in which they were processed, and attempt to
  update it.
* If parallel builds (see Section 5.4 [Parallel Execution], page 51) are
  enabled then makefiles will be rebuilt in parallel as well.

'''

* If a makefile has a rule which says how to update it (found either in that
  very makefile or in another one) or if an implicit rule applies to it (see
  Chapter 10 [Using Implicit Rules], page 121), it will be updated if
  necessary.
* After all makefiles have been checked, if any have actually been changed,
  `make` starts with a clean slate and reads all the makefiles over again.
* (It will also attempt to update each of them over again, but normally this
  will not change them again, since they are already up to date.)
* Each restart will cause the special variable `MAKE_RESTARTS` to be updated
  (see Section 6.14 [Special Variables], page 80).

'''

* If you know that one or more of your makefiles cannot be remade and you want
  to keep `make` from performing an implicit rule search on them, perhaps for
  efficiency reasons, you can use any normal method of preventing implicit
  rule look-up to do so.
* For example, you can write an explicit rule with the makefile as the target,
  and an empty recipe (see Section 5.9 [Using Empty Recipes], page 62).

'''

* If the makefiles specify a double-colon rule to remake a file with a recipe
  but no prerequisites, that file will always be remade (see Section 4.12
  [Double-Colon], page 42).
* In the case of makefiles, a makefile that has a double-colon rule with a
  recipe but no prerequisites will be remade every time `make` is run, and
  then again after `make` starts over and reads the makefiles in again.
* This would cause an infinite loop: `make` would constantly remake the
  makefile and restart, and never do anything else.
* So, to avoid this, `make` will not attempt to remake makefiles which are
  specified as targets of a double-colon rule with a recipe but no
  prerequisites.

'''

* Phony targets (see Section 4.5 [Phony Targets], page 31) have the same
  effect: they are never considered up-to-date and so an included file marked
  as phony would cause `make` to restart continuously.
* To avoid this `make` will not attempt to remake makefiles which are marked
  phony.
* You can take advantage of this to optimize startup time: if you know you
  don't need your `Makefile` to be remade you can prevent `make` from trying
  to remake it by adding either:
+
[source,makefile]
.PHONY: Makefile
+
or:
+
[source,makefile]
Makefile:: ;

'''

* If you do not specify any makefiles to be read with '```-f```' or
  '```--file```' options, `make` will try the default makefile names; see
  Section 3.2 [What Name to Give Your Makefile], page 12.
* Unlike makefiles explicitly requested with '```-f```' or '```--file```'
  options, `make` is not certain that these makefiles should exist.
* However, if a default makefile does not exist but can be created by running
  `make` rules, you probably want the rules to be run so that the makefile can
  be used.

'''

* Therefore, if none of the default makefiles exists, make will try to make
  each of them until it succeeds in making one, or it runs out of names to
  try.
* Note that it is not an error if make cannot find or make any makefile; a
  makefile is not always necessary.
