= 4 Writing Rules
:toc: left
:source-highlighter: rouge

* A _rule_ appears in the makefile and says when and how to remake certain
  files, called the rule's _targets_.
* It lists the other files that are the _prerequisites_ of the target, and the
  _recipe_ to use to create or update the target.

'''

* The order of rules is not significant, except for determining the _default
  goal_: the target for `make` to consider, if you do not otherwise specify
  one.
* The default goal is the first target of the first rule in the first makefile.
* There are two exceptions: a target starting with a period is not a default
  unless it also contains one or more slashes, \'``/``'; and, a target that
  defines a pattern rule has no effect on the default goal.
* (See Section 10.5 [Defining and Redefining Pattern Rules].)

'''

* Therefore, we usually write the makefile so that the first rule is the one
  for compiling the entire program or all the programs described by the
  makefile (often with a target called \'``all``').
* See Section 9.2 [Arguments to Specify the Goals].

== 4.1 Rule Syntax

* In general, a rule looks like this:
+
[source,makefile,subs=+quotes]
_targets_: _prerequisites_
	_recipe_
	...

* or like this:
+
[source,makefile,subs=+quotes]
_targets_: _prerequisites_; _recipe_
	_recipe_
	...

* The _targets_ are file names, seperated by spaces.
* Wildcard characters may be used +
  (see Section 4.3 [Using Wildcard Characters in File Names])
  and a name of the form `_a_(_m_)` represents member _m_ in archive file _a_ +
  (see Section 11.1 [Archive Members as Targets]).
* Usually there is only one target per rule, but occasionally there is a reason
  to have more +
  (see Section 4.9 [Multiple Targets in a Rule]).

'''

* The _recipe_ lines start with a tab character.
* The first recipe line may appear on the line after the prerequisites, with a
  tab character, or may appear on the same line, with a semicolon.
* Either way, the effect is the same.
* There are other differences in the syntax of recipes.
* See Chapter 5 [Writing Recipes in Rules].

'''

* Because dollar signs are used to start `make` variable references, if you
  really want to a dollar sign in a target or prerequisite you must write two
  of them, \'``$$`' +
  (see Chapter 6 [How to Use Variables]).
* If you have enabled secondary expansion and you want a literal dollar sign in
  the prerequisites list, you must actually write _four_ dollar sign
  (\'``$$$$``').

'''

* You may split a long line by inserting a backslash followed by a newline, but
  this is not required, as `make` places no limit on the length of a line in a
  makefile.

'''

* A rule tells `make` two things: when the targets are out of date, and how to
  update them when necessary.

'''

* The criterion for being out of date is specified in terms of the
  _prerequisites_, which consist of file names separated by spaces.
* (Wildcards and archive members +
  (see Chapter 11 [Archives]) +
  are allowed here too.)
* A target is out of date if it does not exist or if it is older than any of
  the prerequisites.

'''

* How to update is specified by a _recipe_.
* This is one or more lines to be executed by the shell, but with some extra
  features +
  (see Chapter 5 [Writing Recipes in Rules]).

== 4.2 Types of Prerequisites

* There are two different types of prerequisites understood by GNU `make`:
  normal prerequisites, described in the previous section, and _order-only_
  prerequisites.
* A normal prerequisite makes two statements: first, it imposes an order in
  which recipes will be invoked: the recipes for all prerequisites of a target
  will be completed before the recipe for the target is started.
* Second, it imposes a dependency relationship: if any prerequisite is newer
  than the target, then the target is considered out-of-date and must be
  rebuilt.

'''

* Occasionally you may want to ensure that a prerequisite is built before a
  target, but _without_ forcing the target to be updated if the prerequisite is
  updated.
* _Order-only_ prerequisites are used to create this type of relationship.
* Order-only prerequisites can be specified by placing a pipe symbol (`|`) in
  the prerequisites list: any prerequisites to the left of the pipe symbol are
  normal; any prerequisites to the right are order-only:
+
[source,makefile,subs=+quotes]
_targets_ : _normal-prerequisites_ | _order-only-prerequisites_

'''

* The normal prerequisites section may of course be empty.
* Also, you may still declare multiple lines of prerequisites for the same
  target: they are appended appropriately (normal prerequisites are appended to
  the list of normal prerequisites; order-only prerequisites are appended to
  the list of order-only prerequisites).
* Note that if you declare the same file to be both a normal and an order-only
  prerequisite, the normal prerequisite takes precedence (since they have a
  strict superset of the behavior of an order-only prerequisite).

'''

* Order-only prerequisites are never checked when determining if the target is
  out of date; even order-only prerequisites marked as phony (see Section 4.5
  [Phony Targets], page 31) will not cause the target to be rebuilt.

'''

* Consider an example where your targets are to be placed in a separate
  directory, and that directory might not exist before `make` is run.
* In this situation, you want the directory to be created before any targets
  are placed into it but, because the timestamps on directories change where a
  file is added, removed, or renamed, we certainly don't want to rebuild all the
  targets whenever the directory's timestamp changes.
* One way to manage this is with order-only prerequisites: make the directory
  an order-only prerequisite on all the targets:
+
[,makefile]
----
OBJDIR := objdir
OBJS := (addprefix $(OBJDIR)/,foo.o bar.o baz.o)

$(OBJDIR)/%.o : %.c
	$(COMPILE.c) $(OUTPUT_OPTION) $<

all: $(OBJS)

$(OBJS): | $(OBJDIR)

$(OBJDIR):
	mkdir $(OBJDIR)
----

'''

* Now the rule to create the `objdir` directory will be run, if needed, before
  any, before any '.o' is built, but no '.o' will be built because the `objdir`
  directory timestamp changed.

== 4.3 Using Wildcard Characters in File Names

* A single file name can specify many files using *_wildcard_ characters*.
* The wildcard characters in `make` are \'``*``', \'``?``' and \'``[...]``',
  the same as in the Bourne shell.

'''

* If an expression matches multiple files then the results will be sorted.
* However multiple expressions will not be globally sorted.

'''

* The character \'``~``' at the beginning of a file name also has special
  significance.
* If alone, or followed by a slash, it represents your home directory.
* If the \'``~``' is followed by a word, the string represents the home
  directory of the use named by that word.

'''

* Wildcard expansion is performed by `make` automatically in targets and in
  prerequisites.
* In recipes, the shell is responsible for wildcard expansion.
* In other contexts, wildcard expansion happens only if you request it
  explicitly with the `wildcard` function.

'''

* The special significance of a wildcard characters can be turned off by
  preceding it with a backslash.

=== 4.3.1 Wildcard Examples

* With the following rule in the makefile, \'``make print``' will print all the
  \'``.c``' files that have changed since the last time you printed them:
+
[source,makefile]
print: *.c
	lpr -p $?
	touch print

* This rule uses `print` as an empty target file; see Section 4.7 [Empty Target
  Files to Record Events].
* (The automatic variable \'``$?``' is used to print only those files that have
  changed; see Section 10.5.3 [Automatic Variables].)

=== 4.3.3 The Function `wildcard`

* Wildcard expansion does not normally take place when a variable is set, or
  inside the arguments of a function.
* If you want to do wildcard expansion in such places, you need to use the
  `wildcard` function, like this:
+
[source,makefile,subs=+quotes]
$(wildcard _pattern_...)

* This string, used anywhere in a makefile, is replaced by a space-separated
  list of names of existing files that match one of the given file name
  patterns.
* If no existing file name matches a pattern, then that pattern is omitted from
  the output of the `wildcard` function.
* The results of the `wildcard` function are sorted.
* Each individual expression is sorted separately.

'''

* We can change the list of C source files into a list of object files by
  replacing the '`.c`' suffix with '`.o`' in the result, like this:
+
[source,makefile]
$(patsubst %.c,%.o,$(wildcard *.c))

* (See Section 8.2 [Functions for String Substitution and Analysis].)

'''

* Thus, a makefile to compile all C source files in the directory and then link
  them together could be written as follows:
+
[,makefile]
----
objects := $(patsubst %.c,%.o,$(wildcard *.c))

foo: $(objects)
	cc -o foo $(objects)
----

* See Section 6.2 [The Two Flavors of Variables] for an explanation of
  \'``:=``', which is a variant of \'``=``'.

== 4.4 Searching Directories for Prerequisites

* For large systems, it is often desirable to put sources in a separate
  directory from the binaries.
* The _directory search_ features of `make` facilitate this by searching
  several directories automatically to find a prerequisite.
* When you redistribute the files among directories, you do not need to change
  the individual rules, just the search paths.

=== 4.4.1 `VPATH`: Search Path for All Prerequisites

* The value of the `make` variable `VPATH` specifies a list of directories
  that `make` should search.
* Most often, the directories are expected to contain prerequisite files that
  are not in the current directory; however, `make` uses `VPATH` as a search
  list for both prerequisites and targets of rules.

'''

* Thus, if a file that is listed as a target or prerequisite does not exist in
  the current directory, `make` searches the directories listed in `VPATH` for
  a file with that name.
* If a file is found in one of them, that file may become the prerequisite
  (see below).
* Rules may then specify the names of files in the prerequisite list as if
  they all existed in the current directory.
* See Section 4.4.4 [Writing Recipes with Directory Search], page 30.

'''

* In the `VPATH` variable, directory names are separated by colons or blanks.
* The order in which directories are listed is the order followed by `make` in
  its search.
* (On MS-DOS and MS-Windows, semi-colons are used as separators of directory
  names in `VPATH`, since the colon can be used in the pathname itself, after
  the drive letter.)

'''

* For example,
+
....
VPATH = src:../headers
....
+
specifies a path containing two directories, `src` and `../headers`, which
`make` searches in that order.

'''

* With this value of `VPATH`, the following rule,
+
....
foo.o : foo.c
....
+
is interpreted as if it were written like this:
+
....
foo.o : src/foo.c
....
+
assuming the file `foo.c` does not exist in the current directory but is found
in the directory `src`.

=== 4.4.2 The `vpath` Directive

* Similar to the `VPATH` variable, but more selective, is the `vpath`
  directive (note lower case), which allows you to specify a search path for a
  particular class of file names: those that match a particular pattern.
* Thus you can supply certain search directories for one class of file names
  and other directories (or none) for other file names.
* There are three forms of the `vpath` directive:

'''

`vpath _pattern_ _directories_`::
* Specify the search path _directories_ for file names that match _pattern_.
* The search path, _directories_, is a list of directories to be searched,
  separated by colons (semi-colons on MS-DOS and MS-Windows) or blanks, just
  like the search path used in the `VPATH` variable.
`vpath _pattern_`::
* Clear out the search path associated with _pattern_.
`vpath`::
* Clear all search paths previously specified with `vpath` directives.

'''

* A `vpath` pattern is a string containing a '%' character.
* The string must match the file name of a prerequisite that is being searched
  for, the '%' character matching any sequence of zero or more characters (as
  in pattern rules; see Section 10.5 [Defining and Redefining Pattern Rules],
  page 129).
* For example, `%.h` matches files that end in `.h`.
* (If there is no '%', the pattern must match the prerequisite exactly, which
  is not useful very often.)

'''

* '%' characters in a `vpath` directive's pattern can be quoted with preceding
  backslashes ('\').
* Backslashes that would otherwise quote '%' characters can be quoted with
  more backslashes.
* Backslashes that quote '%' characters or other backslashes are removed from
  the pattern before it is compared to file names.
* Backslashes that are not in danger of quoting '%' characters go unmolested.

'''

* When a prerequisite fails to exist in the current directory, if the
  _pattern_ in a `vpath` directive matches the name of the prerequisite file,
  then the directories in that directive are searched just like (and before)
  the directories in the `VPATH` variable.

'''

* For example,
+
[source,makefile]
vpath %.h ../headers
+
tells make to look for any prerequisite whose name ends in `.h` in the
directory `../headers` if the file is not found in the current directory.

'''

* If several `vpath` patterns match the prerequisite file's name, then `make`
  processes each matching `vpath` directive one by one, searching all the
  directories mentioned in each directive.
* `make` handles multiple `vpath` directives in the order in which they appear
  in the makefile; multiple directives with the same pattern are independent
  of each other.

'''

* Thus,
+
[,makefile]
----
vpath %.c foo
vpath % blish
vpath %.c bar
----
+
will look for a file ending in '.c' in `foo`, then `blish`, then `bar`, while
+
[,makefile]
----
vpath %.c foo:bar
vpath % blish
----
+
will look for a file ending in '.c' in `foo`, then `bar`, then `blish`.

=== 4.4.4 Writing Recipes with Directory Search

* When a prerequisite is found in another directory through directory search,
  this cannot change the recipe of the rule; they will execute as written.
* Therefore, you must write the recipe with care so that it will look for the
  prerequisite in the directory where `make` finds it.

'''

* This is done with the _automatic variables_ such as '$^' (see Section 10.5.3
  [Automatic Variables], page 130).
* For instance, the value of '$^' is a list of all the prerequisites of the
  rule, including the names of the directories in which they were found, and
  the value of '$@' is the target.
* Thus:

[,makefile]
----
foo.o : foo.c
	cc -c $(CFLAGS) $^ -o $@
----

* (The variable `CFLAGS` exists so you can specify flags for C compilation by
  implicit rules; we use it here for consistency so it will affect all C
  compilations uniformly; see Section 10.3 [Variables Used by Implicit Rules],
  page 125.)

'''

* Often the prerequisites include header files as well, which you do not want
  to mention in the recipe.
* The automatic variable '$<' is just the first prerequisite:

[,makefile]
----
VPATH = src:../headers
foo.o : foo.c defs.h hack.h
	cc -c $(CFLAGS) $< -o $@
----

== 4.5 Phony Targets

* A phony target is one that is not really the name of a file; rather it is
  just a name for a recipe to be executed when you make an explicit request.
* There are two reasons to use a phony target: to avoid a conflict with a file
  of the same name, and to improve performance.

'''

* If you write a rule whose recipe will not create the target file, the recipe
  will be executed every time the target comes up for remaking.
* Here is an example:
+
[source,makefile]
clean:
	rm *.o temp

* In this example, the `clean` target will not work properly if a file named
  `clean` is ever created in this directory.
* Since it has no prerequisites, `clean` would always be considered up to date
  and its recipe would not be executed.
* To avoid this problem you can explicitly declare the target to be phony by
  making it a prerequisite of the special target `.PHONY` +
  (see Section 4.8 [Special Built-in Target Names]) as follows:
+
[source,makefile]
.PHONY: clean
clean:
	rm *.o temp

* Once this is done, \'``make clean``' will run the recipe regardless of
  whether there is a file named `clean`.

'''

* Prerequisites of `.PHONY` are always interpreted as literal target names,
  never as patterns.

'''

* Phony targets are also useful in conjunction with recursive invocations of
  `make` (see Section 5.7 [Recursive Use of `make`]).

== 4.7 Empty Target Files to Record Events

* The empty target is a variant of the phony target; it is used to hold recipes
  for an action that you request explicitly from time to time.
* Unlike a phony target, this target file can really exist; but the file's
  contents do not matter, and usually are empty.

'''

* The purpose of the empty target file is to record, with its last-modification
  time, when the rule's recipe was last executed.
* It does so because one of the commands in the recipe is a `touch` command to
  update the target file.

'''

* The empty target file should have some prerequisites (otherwise it doesn't
  make sense).
* When you ask to remake the empty target, the recipe is executed if any
  prerequisite is more recent than the target; in other words, if a
  prerequisite has changed since the last time you remade the target.
* Here is an example:
+
[source,makefile]
print: foo.c bar.c
	lpr -p $?
	touch print

* With this rule, \'``make print``' will execute the `lpr` command if either
  source file has changed since the last \'``make print``'.
* The automatic variable \'``$?``' is used to print only those files that have
  changed (see Section 10.5.3 [Automatic Variables]).

== 4.9 Multiple Targets in a Rule

* When an explicit rule has multiple targets they can be treated in one of two
  possible ways: as independent targets or as grouped targets.
* The manner in which they are treated is determined by the separator that
  appears after the list of targets.

=== Rules with Independent Targets

* Rules that use the standard target separator, `:`, define independent
  targets.
* This is equivalent to writing the same rule once for each target, with
  duplicated prerequisites and recipes.
* Typically, the recipe would use automatic variables such as \'``$@``' to
  specify which target is being built.

'''

* Rules with independent targets are useful in two cases:
** You want just prerequisites, no recipe. +
   For example:
+
[source,makefile]
kbd.o command.o files.o: command.h
+
gives an additional prerequisite to each of the three object files
mentioned. +
It is equivalent to writing:
+
[source,makefile]
kbd.o: command.h
command.o: command.h
files.o: command.h

** Similar recipes work for all the targets. +
   The automatic variable \'``$@``' can be used to substitute the particular
   target to be remade into the commands (see Section 10.5.3 [Automatic
   Variables], page 130). +
   For example:
+
[source,makefile]
bigoutput littleoutput : text.g
	generate text.g -$(subst output,,$@) > $@
+
is equivalent to
+
[source,makefile]
bigoutput : text.g
	generate text.g -big > bigoutput
littleoutput : text.g
	generate text.g -little > littleoutput
+
Here we assume the hypothetical program `generate` makes two types of output,
one if given \'``-big``' and one if given \'``-little``'. +
See Section 8.2 [Functions for String Substitution and Analysis], page 92, for
an explanation of the `subst` function.

'''

* Suppose you would like to vary the prerequisites according to the target,
  much as the variable \'``$@``' allows you to vary the recipe.
* You cannot do this with multiple targets in an ordinary rule, but you can do
  it with a static pattern rule.
* See Section 4.11 [Static Pattern Rules], page 40.

== 4.10 Multiple Rules for One Target

* One file can be the target of several rules.
* All the prerequisites mentioned in all the rules are merged into one list of
  prerequisites for the target.
* If the target is older than any prerequisite from any rule, the recipe is
  executed.

'''

* There can only be one recipe to be executed for a file.
* If more than one rule gives a recipe for the same file, `make` uses the last
  one given and prints an error message.
* (As a special case, if the file's name begins with a dot, no error message
  is printed. +
  This odd behavior is only for compatibility with other implementations of
  `make`... you should avoid using it).
* Occasionally it is useful to have the same target invoke multiple recipes
  which are defined in different parts of your makefile; you can use
  double-colon rules (see Section 4.12 [Double-Colon], page 42) for this.

'''

* An extra rule with just prerequisites can be used to give a few extra
  prerequisites to many files at once.
* For example, makefiles often have a variable, such as `objects`, containing
  a list of all the compiler output files in the system being made.
* An easy way to say that all of them must be recompiled if `config.h` changes
  is to write the following:
+
[source,makefile]
objects = foo.o bar.o
foo.o : defs.h
bar.o : defs.h test.h
$(objects) : config.h

* This could be inserted or taken out without changing the rules that really
  specify how to make the object files, making it a convenient form to use if
  you wish to add the additional prerequisite intermittently.

'''

* Another wrinkle is that the additional prerequisites could be specified with
  a variable that you set with a command line argument to `make (see Section
  9.5 [Overriding Variables], page 113).
* For example,
+
[source,makefile]
extradeps=
$(objects) : $(extradeps)
+
means that the command \'``make extradeps=foo.h``' will consider `foo.h` as a
prerequisite of each object file, but plain \'``make``' will not.

'''

* If none of the explicit rules for a target has a recipe, then make searches
  for an applicable implicit rule to find one see Chapter 10 [Using Implicit
  Rules], page 121).

== 4.13 Generating Prerequisites Automatically

* In the makefile for a program, many of the rules you need to write often say
  only that some object file depends on some header file.
* For example, if `main.c` uses `defs.h` via an `#include`, you would write:

[source,makefile]
main.o: defs.h

* You need this rule so that make knows that it must remake `main.o` whenever
  `defs.h` changes.
* You can see that for a large program you would have to write dozens of such
  rules in your makefile.
* And, you must always be very careful to update the makefile every time you
  add or remove an `#include`.

'''

* To avoid this hassle, most modern C compilers can write these rules for you,
  by looking at the `#include` lines in the source files.
* Usually this is done with the \'``-M``' option to the compiler.
* For example, the command:
+
....
cc -M main.c
....
+
generates the output:
+
....
main.o : main.c defs.h
....

* Thus you no longer have to write all those rules yourself.
* The compiler will do it for you.

'''

* Note that such a rule constitutes mentioning `main.o` in a makefile, so it
  can never be considered an intermediate file by implicit rule search.
* This means that `make` won't ever remove the file after using it; see Section
  10.4 [Chains of Implicit Rules], page 127.

'''

* With old `make` programs, it was traditional practice to use this compiler
  feature to generate prerequisites on demand with a command like \'``make
  depend``'.
* That command would create a file `depend` containing all the
  automatically-generated prerequisites; then the makefile could use include
  to read them in (see Section 3.3 [Include], page 13).

'''

* In GNU `make`, the feature of remaking makefiles makes this practice
  obsolete -- you need never tell `make` explicitly to regenerate the
  prerequisites, because it always regenerates any makefile that is out of
  date.
* See Section 3.5 [Remaking Makefiles], page 15.

'''

* The practice we recommend for automatic prerequisite generation is to have
  one makefile corresponding to each source file.
* For each source file `_name_.c` there is a makefile `_name_.d` which lists
  what files the object file `_name_.o` depends on.
* That way only the source files that have changed need to be rescanned to
  produce the new prerequisites.

'''

* Here is the pattern rule to generate a file of prerequisites (i.e., a
  makefile) called `_name_.d` from a C source file called `_name_.c`:

[source,makefile]
%.d: %.c
	@set -e; rm -f $@; \
	$(CC) -M $(CPPFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$

* See Section 10.5 [Pattern Rules], page 129, for information on defining
  pattern rules.
* The '-e' flag to the shell causes it to exit immediately if the `$(CC)`
  command (or any other command) fails (exits with a nonzero status).

'''

* With the GNU C compiler, you may wish to use the \'``-MM``' flag instead of
  \'``-M``'.
* This omits prerequisites on system header files.
* See Section "Options Controlling the Preprocessor" in Using GNU CC, for
  details.

'''

* The purpose of the `sed` command is to translate (for example):

[source,makefile]
main.o : main.c defs.h
+
into:
+
[source,makefile]
main.o main.d : main.c defs.h

* This makes each \'``.d``' file depend on all the source and header files
  that the corresponding \'``.o``' file depends on.
* `make` then knows it must regenerate the prerequisites whenever any of the
  source or header files changes.

'''

* Once you've defined the rule to remake the \'``.d``' files, you then use the
  `include` directive to read them all in.
* See Section 3.3 [Include], page 13.
* For example:

[,makefile]
----
sources = foo.c bar.c

include $(sources:.c=.d)
----

* (This example uses a substitution variable reference to translate the list
  of source files \'``foo.c bar.c``' into a list of prerequisite makefiles,
  \'``foo.d bar.d``'. +
  See Section 6.3.1 [Substitution Refs], page 69, for full information on
  substitution references.)
* Since the \'``.d``' files are makefiles like any others, `make` will remake
  them as necessary with no further work from you.
* See Section 3.5 [Remaking Makefiles], page 15.

'''

* Note that the \'``.d``' files contain target definitions; you should be sure
  to place the `include` directive _after_ the first, default goal in your
  makefiles or run the risk of having a random object file become the default
  goal.
* See Section 2.3 [How Make Works], page 5.
